public enum GameType
{
    PLAYER, PLATFORM, PORTALT, PORTAL1, PORTAL2, PORTAL3, PORTAL4, TEXT,
    FIREBALL, ENEMY, DOOM, GROUND, BIG_PLATFORM, HIGH_PLATFORM, CLOUD_PLATFORM,
    PIPE, STAR, COIN, FEATHER, BOSS, BOSSPLATFORM, BDOOM
}
